### ISSUE TITLE
question : what is the purpose of this mod ? i read readme

### ISSUE THREAD

**Issue by yesn0t** [PyPylia/clientgive#1]
is this the same as the vanilla /give command ?
/give works outside of creative mode too

**Comment by PyPylia** [comment]
This is similar, but it is different in one key factor.
This works using the `CreativeInventoryActionC2SPacket`, not using a server-sided command.
This means that it will work even without permission to use the `/give` command, such as not being a server operator.
This also spawns the items directly into the inventory instead of first spawning them as an item.

**Comment by yesn0t** [comment]
got it, thanks !
